# config.yaml - Cleaned Application Configuration File (Respecting Existing Structure)

# Database Configuration
database:
  filemaker:
    server: "${FILEMAKER_SERVER:localhost}"
    port: "${FILEMAKER_PORT:2399}"
    user: "${FILEMAKER_USER:admin}"
    password: "${FILEMAKER_PASSWORD:password}"
    database: "${FILEMAKER_DATABASE:CrownMaster}"
    fmjdbc_jar_path: "libs/fmjdbc.jar"
    connection_timeout: 30
    retry_attempts: 3

  iseries:
    server: "${ISERIES_SERVER:localhost}"
    user: "${ISERIES_USER:admin}"
    password: "${ISERIES_PASSWORD:password}"
    database: "${ISERIES_DATABASE:DSTDATA}"
    jt400_jar_path: "libs/jt400.jar"
    connection_timeout: 30
    retry_attempts: 3

# File Paths Configuration
files:
  # Input files
  lookup_file: "data/application_replacements.json"
  sdc_blank_template: "data/SDC_Blank_Template.xlsx"
  missing_parts_list: "data/sdc_missing.txt"

  # Output files
  application_data: "output/application_data.xlsx"
  popularity_codes: "output/popularity_codes.csv"
  sdc_populated_template: "output/SDC_Populated_Template.xlsx"
  marketing_validation_report: "output/marketing_validation_report.xlsx"
  upc_validation_report: "output/upc_validation_report.xlsx"
  measurement_validation_report: "output/measurement_validation_report.xlsx"
  cost_discrepancy_report: "output/cost_discrepancy_report.xlsx"
  kit_components_report: "output/kit_components_report.xlsx"

  # Directories
  backup_dir: "backups"
  log_file: "logs/application.log"
  query_templates_dir: "src/infrastructure/repositories/query_templates"

# Data Validation Configuration
validation:
  # Year validation
  vehicle_start_year: 1900
  vehicle_end_year: 2026
  max_year_range: 50
  future_years_allowed: 1

  # UPC validation
  upc_validation:
    enabled: true
    check_duplicates: true
    validate_check_digit: true
    allowed_lengths: [12, 13, 14]

  # Measurement validation
  measurement_validation:
    enabled: true
    max_length_inches: 240.0
    max_width_inches: 120.0
    max_height_inches: 120.0
    max_weight_pounds: 1000.0
    tolerance_percentage: 5.0
    validate_dimensional_weight: true

  # Note validation patterns
  valid_note_prefixes:
    - "w/ "
    - "- "
    - "w/o "
    - "("
    - "lhd"
    - "rhd"
    - ";"
    - "after "
    - "before "
    - "front"
    - "rear"
    - "tagged"
    - "non-export"
    - "2-door"
    - "4-door"
    - "2 door"
    - "4 door"
    - "< "
    - "except "
    - "instrument"
    - "thru "
    - "up to "
    - "usa"
    - "for us"
    - "germany"
    - "fits "
    - "export"
    - "all countries"
    - "all markets"
    - "until "
    - "production"

# Marketing Descriptions Configuration
marketing_descriptions:
  require_jeep_description: true
  require_non_jeep_description: false
  max_description_length: 2000
  min_description_length: 10
  validate_content_quality: true
  check_placeholder_text: true

# Processing Configuration
processing:
  batch_size: 1000
  enable_parallel: false
  max_workers: 4
  memory_limit_mb: 2048

# Popularity Codes Configuration
popularity_codes:
  default_branch: "1"
  default_brand: "All"
  start_date_format: "%Y%m%d"
  default_start_date: "20250101"

  # Popularity thresholds
  thresholds:
    top_tier: 60.0      # A: Top 60%
    second_tier: 20.0   # B: Next 20%
    third_tier: 15.0    # C: Next 15%
    bottom_tier: 5.0    # D: Last 5%

# SDC Template Configuration
sdc_template:
  # Field limits
  field_limits:
    abbreviated_description: 12
    short_description: 20
    invoice_description: 40
    bullet_points_max: 240

# Output Configuration
output:
  excel:
    include_formatting: true
    auto_filter: true
    freeze_headers: true
    max_column_width: 50
    generate_summary: true

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_file_size_mb: 10
  backup_count: 5
  console_output: true

  # Module-specific log levels
  loggers:
    "database": "INFO"
    "validation": "WARNING"
    "workflow": "INFO"

# Error Handling
error_handling:
  continue_on_error: true
  max_errors_per_batch: 100
  error_reporting: "detailed"  # "summary", "detailed", "none"
  save_error_details: true

# Workflow Configuration (Using Existing Workflow Engine)
workflow:
  enabled_steps:
    - "applications"
    - "marketing_descriptions"
    - "popularity_codes"
    - "sdc_template"
    - "validation_reports"

  step_dependencies:
    applications: []
    marketing_descriptions: []
    popularity_codes: []
    sdc_template: ["applications", "marketing_descriptions"]
    validation_reports: ["applications", "marketing_descriptions"]

  # Workflow execution settings
  max_parallel_steps: 3
  default_timeout_minutes: 30
  continue_on_error: true
  retry_failed_steps: false
  max_retries: 2